### ISSUE TITLE
Badly documented error / functionality when no sessions were found from specified range in get_session_dataset

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cdp-data#8]
When `datasets.get_session_dataset` is provided a date range that results in no events found, the following error is produced: 

```python
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maxfield/active/cdp/speakerbox/test.py", line 30, in <module>
    datasets.get_session_dataset(
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/cdp_data/datasets.py", line 342, in get_session_dataset
    sessions = db_utils.load_model_from_pd_columns(
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/cdp_data/utils/db_utils.py", line 193, in load_model_from_pd_columns
    {"model": models_to_join.loc[0].model.collection_name},
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/pandas/core/indexing.py", line 1202, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/pandas/core/indexing.py", line 1153, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/pandas/core/generic.py", line 3864, in xs
    loc = index.get_loc(key)
  File "/home/maxfield/miniconda3/envs/speakerbox/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

We should simply check the length of the produced dataframe and return early with a better error.

**Comment by kristopher-smith** [comment]
Commenting here because the YouTube video said I should.

I have fixed this here: 12e5ae0018beaa85ec01227a67cec81995505794

Current error message displays: "The selected date range returned no session records."  

I originally had a hint for how to fix the issue as well but the error starting looking like a Leo Tolstoy novel.

Happy to change any wording or add to it.

**Comment by evamaxfield** [comment]
Thanks! It is better than before but after you pushed this commit I thought about it for a quick second and thought... "why dont we just return an empty dataframe (but with the right column names) that way if someone is running a bunch of these and concatinating them, the error doesn't cause any problems.

Also in the future, please go through the PR process as it will pick up the lint error. But no worries! Thanks again :heart:

**Comment by kristopher-smith** [comment]
10-4

Thanks for the patience!

**Comment by kristopher-smith** [comment]
I like the idea of an empty df.
